# Generated by Django 5.1.7 on 2025-03-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-views']},
        ),
    ]
